apiVersion: v1
kind: Pod
spec:
  containers:
    - volumeMounts:
      - name: config-volume
        mountPath: {{ .SecretPathKafkaJaas }}
  volumes:
    - name: config-volume
      configMap:
        name: {{ .SecretNameKafkaJaas }}
