---
name: "end to end tests"
on:
  push:
  pull_request:
    branches:
      - main
env:
  CIUXCONFIG: /tmp/ciux.sh
  CIUX_VERSION: v0.0.2-rc1
jobs:
  e2e:
    name: e2e tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.21.4'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install ciux
        run: go install github.com/k8s-school/ciux@"${{ env.CIUX_VERSION }}"
      - name: Build finkctl
        run: |
          go install .
      - name: Ciux project ignition
        run: |
          ciux ignite --selector ci $PWD
      - name: Run e2e test
        run: |
          ./_e2e/e2e.sh
