---
name: "end to end tests"
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  e2e:
    name: e2e tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.21.4'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build finkctl
        run: |
          go install .
      - name: Run raw2science test
        run: |
          ./_e2e/raw2science.sh
